[package]
name = "three_three_dee_dee"
version = "0.1.0"
edition = "2024"

[dependencies]
winit = "0.30"
wgpu = "25.0"
pollster = "0.3"
env_logger = "0.11"
fbx = "0.2.0"
bytemuck = { version = "1.14", features = ["derive"] }
wgpu_text = "0.9"
